version: '3.8'

services:
  postgres:
    image: ankane/pgvector
    container_name: pgvector
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    volumes:
      - /c/path/to/your/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"