services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: dhodb
    env_file:
      - .env
    volumes:
      - ${HOME}/dhoDB:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always
    command: ["postgres", "-c", "shared_preload_libraries=vector"]

  searchapi:
    image: dhosearchapi:0.1
    container_name: dhosearch
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    restart: always